cache:
  npm: true
  directories:
  - "~/.cache"
install:
- npm ci
- npm run build
before_script:
- npm start -- --silent &
script:
- "$(npm bin)/cypress run"
language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: YB987d4Tqm+zg+VSFuYrdfNfqvhdoi09YLQUjb/jS22teMpP/jToyvvMMVWadQMDP26/KrYRxl/0fA/tF7XWwiPeqojMoj00BeAEEV1R+1OnbOra6pLN63g1/Tmzc3Wg/e+pOOF0bqUbBWYjRQBTnQvFARPDDMsnTnRlWcKqkPShiH8M/bwdSypnh+blECpdE4MFW9YHOtY10mZHSRUsZskDcqujcI2h3nmpAC0LfdXngSsv3Y/jwOpMSe5OiWyootr7rXvTVXHdtRLN8Av8GIlqP+yYOhHA+V0zAnFex8DoqY03o5jgTeTMgg5mMIWry1sfomoZHx0hvx3O1L+IKAYircrp+gCWzyWVr3c7r3+OrwMZFkYr1k6I3VHL1/d8o0on7+qfcurHSGA5rG0q7z+ZORy6HNCdvCE4+TBht1g7WLUE8CT9Oe6yh13v1zDugiZCPzgTKRstmWX2ZLokfI0T59UrwdSQrUPN27IMIIqWyv6TL7BHohAu0ZRNHIIUAWG7wQjhVD97kV/rN9VcH5+jA5k8dbCM+QMmYcS8gTBQV3Q4zmLaV1rxTrDrZFTZ8LJm6kV7aM7P32PUYDbP4wvPx2xyJvqZJZdmMExkY+477n4plEar2Y4AluutOVn3U69Xv1STlucW4A7Q2xxtjTTN3NONKcx98QUkku22caM=
  app: lyric-lava
  on:
    all_branches: true
  skip_cleanup: true
